Holoscan SDK v2.4.0 Release
Co-authored-by: Alexis Girault <agirault@nvidia.com>
Co-authored-by: Andreas Heumann <aheumann@nvidia.com>
Co-authored-by: Connor Smith <cosmith@nvidia.com>
Co-authored-by: Gigon Bae <gbae@nvidia.com>
Co-authored-by: Gregory Lee <grelee@nvidia.com>
Co-authored-by: Ian Stewart <istewart@nvidia.com>
Co-authored-by: Ilies Chergui <ichergui@nvidia.com>
Co-authored-by: Julien Jomier <jjomier@nvidia.com>
Co-authored-by: Tom Birdsong <tbirdsong@nvidia.com>
Co-authored-by: Victor Chang <vicchang@nvidia.com>
Co-authored-by: Wendell Hom <whom@nvidia.com>

diff --git a/python/holoscan/cli/packager/templates/Dockerfile.jinja2 b/python/holoscan/cli/packager/templates/Dockerfile.jinja2
--- a/python/holoscan/cli/packager/templates/Dockerfile.jinja2
+++ b/python/holoscan/cli/packager/templates/Dockerfile.jinja2
@@ -1,26 +1,29 @@
 {#
-    SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
-    SPDX-License-Identifier: Apache-2.0
+SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
+SPDX-License-Identifier: Apache-2.0
 
-    Licensed under the Apache License, Version 2.0 (the "License");
-    you may not use this file except in compliance with the License.
-    You may obtain a copy of the License at
+Licensed under the Apache License, Version 2.0 (the "License");
+you may not use this file except in compliance with the License.
+You may obtain a copy of the License at
 
-    http://www.apache.org/licenses/LICENSE-2.0
+http://www.apache.org/licenses/LICENSE-2.0
 
-    Unless required by applicable law or agreed to in writing, software
-    distributed under the License is distributed on an "AS IS" BASIS,
-    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-    See the License for the specific language governing permissions and
-    limitations under the License.
+Unless required by applicable law or agreed to in writing, software
+distributed under the License is distributed on an "AS IS" BASIS,
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
 #}
 
+ARG GPU_TYPE=dgpu
+
 {% if application_type == 'CppCMake' %}
+# Build C++ application in the builder stage
 FROM {{ build_image }} AS builder
 ENV DEBIAN_FRONTEND=noninteractive
 
 RUN apt-get update && \
-    apt-get install -y jq
+    apt-get install -y --no-install-recommends jq
 
 WORKDIR /src
 COPY ./app/* /src
@@ -38,11 +41,109 @@ RUN rm /install/CMakeCache.txt /install/Makefile /install/cmake_install.cmake &&
     rm -r /install/CMakeFiles/ /install/.cmake/
 {% endif %}
 
-FROM {{ base_image }}
 
+
+FROM {{ base_image }} AS base
+
+RUN apt-get update \
+    && apt-get install -y --no-install-recommends --no-install-suggests \
+        curl \
+        jq \
+    && rm -rf /var/lib/apt/lists/*
+
+{% if 'torch' in includes %}
+# Collect torch dependencies: libtorch, torchvision
+FROM base AS torch-dependencies
+
+ARG GPU_TYPE
+ARG TORCHVISION_VERSION=0.16.0_23.08
+ARG LIBTORCH_VERSION=2.1.0_23.08
+
+# Install openmpi
+RUN apt update && \
+    apt-get install -y --no-install-recommends --no-install-suggests \
+        bzip2 \
+        libopenmpi3=4.1.2-* \
+    && rm -rf /var/lib/apt/lists/*
+
+# Download libtorch
+WORKDIR /opt/libtorch/
+RUN ARCH={{ target_arch }} && if [ "$ARCH" = "aarch64" ]; then ARCH="aarch64-${GPU_TYPE}"; fi && \
+    curl -S  -#  -o libtorch.tgz  -L \
+        https://edge.urm.nvidia.com/artifactory/sw-holoscan-thirdparty-generic-local/libtorch/libtorch-${LIBTORCH_VERSION}-${ARCH}.tar.gz
+RUN mkdir -p ${LIBTORCH_VERSION} && \
+    tar -xf libtorch.tgz -C ${LIBTORCH_VERSION} --strip-components 1 && \
+    rm -f libtorch.tgz && \
+    find . -type f -name "*Config.cmake" -exec sed -i '/kineto/d' {} +
+
+# Download torchvision
+WORKDIR /opt/torchvision/
+RUN ARCH={{ target_arch }} && if [ "$ARCH" = "aarch64" ]; then ARCH="aarch64-${GPU_TYPE}"; fi && \
+    curl -S -# -o torchvision.tgz -L \
+        https://edge.urm.nvidia.com/artifactory/sw-holoscan-thirdparty-generic-local/torchvision/torchvision-${TORCHVISION_VERSION}-${ARCH}.tar.gz
+RUN mkdir -p ${TORCHVISION_VERSION}
+RUN tar -xf torchvision.tgz -C ${TORCHVISION_VERSION} --strip-components 1 && \
+    rm -f torchvision.tgz
+
+# Download HPCX for libucc.so.1
+WORKDIR /opt/hpcx
+RUN curl -S -# -o hpcx.tbz -L \
+    https://www.mellanox.com/downloads/hpc/hpc-x/v2.15/hpcx-v2.15-gcc-inbox-ubuntu22.04-cuda12-gdrcopy2-nccl2.17-{{target_arch}}.tbz && \
+    tar -xvjf hpcx.tbz hpcx-v2.15-gcc-inbox-ubuntu22.04-cuda12-gdrcopy2-nccl2.17-{{target_arch}}/ucc/lib/libucc.so.1.0.0 && \
+    rm -f hpcx.tbz && \
+    find . -name libucc.so.1.0.0 -exec mv -f {} /opt/hpcx/libucc.so.1 \;
+# End collect torch dependencies
+{% endif %}
+
+
+{% if 'onnx' in includes %}
+# Collect onnx dependencies
+FROM base AS onnx-dependencies
+ARG GPU_TYPE
+ARG ONNX_RUNTIME_VERSION=1.15.1_23.08
+
+WORKDIR /opt/onnxruntime
+
+# Download onnx binaries
+RUN curl -S -L -# -o ort.tgz \
+    https://edge.urm.nvidia.com/artifactory/sw-holoscan-thirdparty-generic-local/onnxruntime/onnxruntime-${ONNX_RUNTIME_VERSION}-cuda-12.2-$(uname -m).tar.gz
+RUN mkdir -p ${ONNX_RUNTIME_VERSION}
+RUN tar -xf ort.tgz -C ${ONNX_RUNTIME_VERSION} --strip-components 2 && \
+    rm -f ort.tgz5
+WORKDIR /
+# End collect onnx dependencies
+{% endif %}
+
+# FROM base AS mofed-installer
+# ARG MOFED_VERSION=23.10-2.1.3.1
+
+# # In a container, we only need to install the user space libraries, though the drivers are still
+# # needed on the host.
+# # Note: MOFED's installation is not easily portable, so we can't copy the output of this stage
+# # to our final stage, but must inherit from it. For that reason, we keep track of the build/install
+# # only dependencies in the `MOFED_DEPS` variable (parsing the output of `--check-deps-only`) to
+# # remove them in that same layer, to ensure they are not propagated in the final image.
+# WORKDIR /opt/nvidia/mofed
+# ARG MOFED_INSTALL_FLAGS="--dpdk --with-mft --user-space-only --force --without-fw-update"
+# RUN UBUNTU_VERSION=$(cat /etc/lsb-release | grep DISTRIB_RELEASE | cut -d= -f2) \
+#     && OFED_PACKAGE="MLNX_OFED_LINUX-${MOFED_VERSION}-ubuntu${UBUNTU_VERSION}-$(uname -m)" \
+#     && curl -S -# -o ${OFED_PACKAGE}.tgz -L \
+#         https://www.mellanox.com/downloads/ofed/MLNX_OFED-${MOFED_VERSION}/${OFED_PACKAGE}.tgz \
+#     && tar xf ${OFED_PACKAGE}.tgz \
+#     && MOFED_INSTALLER=$(find . -name mlnxofedinstall -type f -executable -print) \
+#     && MOFED_DEPS=$(${MOFED_INSTALLER} ${MOFED_INSTALL_FLAGS} --check-deps-only 2>/dev/null | tail -n1 |  cut -d' ' -f3-) \
+#     && apt-get update \
+#     && apt-get install --no-install-recommends -y ${MOFED_DEPS} \
+#     && ${MOFED_INSTALLER} ${MOFED_INSTALL_FLAGS} \
+#     && rm -r * \
+#     && apt-get remove -y ${MOFED_DEPS} && apt-get autoremove -y \
+#     && rm -rf /var/lib/apt/lists/*
+
+FROM base AS release
 ENV DEBIAN_FRONTEND=noninteractive
 ENV TERM=xterm-256color
 
+ARG GPU_TYPE
 ARG UNAME
 ARG UID
 ARG GID
@@ -59,10 +160,10 @@ LABEL tag="{{ tag }}"
 LABEL org.opencontainers.image.title="{{ title }}"
 LABEL org.opencontainers.image.version="{{ version }}"
 LABEL org.nvidia.holoscan="{{ holoscan_sdk_version }}"
+
 {% if sdk_type == 'monai-deploy' %}
 LABEL org.monai.deploy.app-sdk="{{ monai_deploy_app_sdk_version }}"
 {% endif %}
-
 
 ENV HOLOSCAN_ENABLE_HEALTH_CHECK=true
 ENV HOLOSCAN_INPUT_PATH={{ full_input_path }}
@@ -76,41 +177,207 @@ ENV HOLOSCAN_CONFIG_PATH={{ config_file_path }}
 ENV HOLOSCAN_APP_MANIFEST_PATH={{ app_json }}
 ENV HOLOSCAN_PKG_MANIFEST_PATH={{ pkg_json }}
 ENV HOLOSCAN_LOGS_PATH={{ logs_dir }}
-ENV PATH=/root/.local/bin:/opt/nvidia/holoscan:$PATH
-ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/libtorch/1.13.1/lib/:/opt/nvidia/holoscan/lib
+ENV HOLOSCAN_VERSION={{ holoscan_sdk_version }}
 
+{% if 'debug' in includes %}
+# Install debugging tools
 RUN apt-get update \
-    && apt-get install -y curl jq \
+    && apt-get install -y --no-install-recommends --no-install-suggests  \
+        build-essential \
+        ccache \
+        gdb \
+        strace \
+        sudo \
+    && rm -rf /var/lib/apt/lists/*
+### End install debugging tools
+{% endif %}
+
+
+{% if 'holoviz' in includes %}
+# Install Holoviz dependencies
+RUN apt-get update \
+    && apt-get install --no-install-recommends --no-install-suggests --allow-downgrades --allow-change-held-packages -y \
+    libvulkan1="1.3.204.1-*" \
+    # X11 support \
+    libgl1="1.4.0-*" \
+    # Wayland support \
+    libwayland-client0="1.20.0-*" \
+    libwayland-egl1="1.20.0-*" \
+    libxkbcommon0="1.4.0-*"  \
+    libdecor-0-plugin-1-cairo="0.1.0-*" \
+    libegl1="1.4.0-*" \
+    && rm -rf /var/lib/apt/lists/*
+# End install Holoviz dependencies
+{% endif %}
+
+
+{% if 'torch' in includes %}
+# Install torch dependencies
+ENV PYTHON_VERSION=3.10.6-1~22.04
+ENV PYTHON_PIP_VERSION=22.0.2+dfsg-1ubuntu0.4
+
+RUN apt update \
+&& apt-get install -y --no-install-recommends --no-install-suggests \
+        python3-minimal=${PYTHON_VERSION} \
+        libpython3-stdlib=${PYTHON_VERSION} \
+        python3=${PYTHON_VERSION} \
+        python3-venv=${PYTHON_VERSION} \
+        python3-pip=${PYTHON_PIP_VERSION} \
+        libjpeg-turbo8="2.1.2-*" \
+        libnuma1="2.0.14-*" \
+        libhwloc15="2.7.0-*" \
+        libopenblas0="0.3.20+ds-*" \
+        libevent-core-2.1-7 \
+        libevent-pthreads-2.1-7 \
+        cuda-cupti-12-2 \
     && rm -rf /var/lib/apt/lists/*
 
+#  mkl - dependency for libtorch plugin on x86_64 (match pytorch container version)
+RUN if [ "{{ cuda_deb_arch }}" = "x86_64" ]; then \
+        python3 -m pip install --no-cache-dir \
+            mkl==2021.1.1 \
+        && \
+        # Clean up duplicate libraries from mkl/tbb python wheel install which makes copies for symlinks.
+        # Only keep the *.so.X libs, remove the *.so and *.so.X.Y libs
+        # This can be removed once upgrading to an MKL pip wheel that fixes the symlinks
+        find /usr/local/lib -maxdepth 1 -type f -regex '.*\/lib\(tbb\|mkl\).*\.so\(\.[0-9]+\.[0-9]+\)?' -exec rm -v {} +; \
+    fi
+
+# Copy Libtorch
+ARG LIBTORCH_VERSION=2.1.0_23.08
+ENV LIBTORCH=/opt/libtorch/${LIBTORCH_VERSION}/lib
+COPY --from=torch-dependencies ${LIBTORCH} ${LIBTORCH}
+
+# Copy TorchVision
+ARG TORCHVISION_VERSION=0.16.0_23.08
+ENV TORCHVISION=/opt/torchvision/${TORCHVISION_VERSION}/lib
+COPY --from=torch-dependencies ${TORCHVISION} ${TORCHVISION}
+
+ENV HPCX=/opt/hpcx/lib
+COPY --from=torch-dependencies /opt/hpcx/libucc.so.1 ${LIBTORCH}/libucc.so.1
+COPY --from=torch-dependencies /usr/lib/{{target_arch}}-linux-gnu/libmpi.so.40 ${LIBTORCH}/libmpi.so.40
+COPY --from=torch-dependencies /usr/lib/{{target_arch}}-linux-gnu/libopen-rte.so.40 ${LIBTORCH}/libopen-rte.so.40
+COPY --from=torch-dependencies /usr/lib/{{target_arch}}-linux-gnu/libopen-pal.so.40 ${LIBTORCH}/libopen-pal.so.40
+
+ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${LIBTORCH}:${TORCHVISION}:${HPCX}
+WORKDIR /
+### End install torch dependencies
+{% endif %}
+
+
+{% if 'onnx' in includes %}
+# Install onnx dependencies
+ARG ONNX_RUNTIME_VERSION=1.15.1_23.08
+ENV ONNX_RUNTIME=/opt/onnxruntime/${ONNX_RUNTIME_VERSION}/lib
+ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${ONNX_RUNTIME}
+
+# Copy ONNX Runtime
+COPY --from=onnx-dependencies ${ONNX_RUNTIME} ${ONNX_RUNTIME}
+
+RUN if [ "${GPU_TYPE}" = "dgpu" ]; then apt-get update \
+    && apt-get install --no-install-recommends --no-install-suggests --allow-downgrades -y \
+        libnvinfer-plugin8="8.6.*+cuda12.0" \
+        libnvonnxparsers8="8.6.*+cuda12.0" \
+        ; fi \
+    && rm -rf /var/lib/apt/lists/* \
+    && rm -f /usr/lib/*/libcudnn*train.so*
+### End install onnx dependencies
+{% endif %}
+
+{% if health_probe is defined %}
+# Install gRPC health probe
+RUN curl -L -o /bin/grpc_health_probe {{ health_probe | pprint }} \
+    && chmod +x /bin/grpc_health_probe && ls -l /bin/grpc_health_probe
+
+HEALTHCHECK --interval=10s --timeout=1s \
+    CMD /bin/grpc_health_probe -addr=:8777 || exit 1
+
+# End install gRPC health probe
+{% endif %}
+
 {% if application_type == 'PythonModule' or application_type == 'PythonFile' %}
-ENV PYTHONPATH="{{ app_dir }}:$PYTHONPATH"
+{% if not 'torch' in includes %}
+# If torch is installed, we can skip installing Python
+ENV PYTHON_VERSION=3.10.6-1~22.04
+ENV PYTHON_PIP_VERSION=22.0.2+dfsg-1ubuntu0.4
+
+RUN apt update \
+    && apt-get install -y --no-install-recommends --no-install-suggests \
+        python3-minimal=${PYTHON_VERSION} \
+        libpython3-stdlib=${PYTHON_VERSION} \
+        python3=${PYTHON_VERSION} \
+        python3-venv=${PYTHON_VERSION} \
+        python3-pip=${PYTHON_PIP_VERSION} \
+    && rm -rf /var/lib/apt/lists/*
+{% endif %}
+
+{% if holoscan_deb_arch == "arm64" %}
+# Requires python3-dev on aarch64
+RUN apt update \
+    && apt-get install -y --no-install-recommends --no-install-suggests \
+        gcc \
+        python3-dev \
+    && rm -rf /var/lib/apt/lists/* 
+{% endif %}
+
 {% endif %}
 
 {% if application_type == 'CppCMake' or application_type == 'Binary' %}
-    {% if custom_base_image == True or custom_holoscan_sdk == True %}
+
+ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/nvidia/holoscan/lib
+
 # Update NV GPG repo key
 # https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/
-RUN if [ $(uname -m) = "aarch64" ]; then ARCH=sbsa; else ARCH=x86_64; fi \
-    && curl -OL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/$ARCH/cuda-keyring_1.0-1_all.deb \
-    && dpkg -i cuda-keyring_1.0-1_all.deb
+RUN curl -OL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/{{ cuda_deb_arch }}/cuda-keyring_1.1-1_all.deb \
+    && dpkg -i cuda-keyring_1.1-1_all.deb \
+    && rm -f cuda-keyring_1.1-1_all.deb \
+    && apt-get update
+
+RUN if [ "{{ holoscan_deb_arch }}" = "arm64" ]; then \
+        GDR_REPO_ARCH=aarch64 ; \
+    else \
+        GDR_REPO_ARCH=x64 ; \
+    fi \
+    && curl -O https://developer.download.nvidia.com/compute/redist/gdrcopy/CUDA%2012.2/ubuntu22_04/${GDR_REPO_ARCH}/libgdrapi_2.4-1_{{ holoscan_deb_arch }}.Ubuntu22_04.deb \
+    && dpkg -i libgdrapi_2.4-1_{{ holoscan_deb_arch }}.Ubuntu22_04.deb \
+    && rm -f libgdrapi_2.4-1_{{ holoscan_deb_arch }}.Ubuntu22_04.deb
+
+{% if custom_holoscan_sdk == True %}
 
 # Use user-specified Holoscan SDK Debian Package
 COPY ./{{ holoscan_sdk_filename }} /tmp/{{ holoscan_sdk_filename }}
-RUN apt-get update \
-    && apt-get install -y /tmp/{{ holoscan_sdk_filename }} \
+RUN apt-get install -y --no-install-recommends --no-install-suggests \
+        /tmp/{{ holoscan_sdk_filename }} \
     && rm -rf /var/lib/apt/lists/*
-    {% else %}
-# Use embedded Holoscan SDK
-{# no op here #}
-    {% endif %}
+
+{% else %}
+
+# Install Holoscan SDK from NVIDIA APT repository
+# Holoscan: available versions (https://pypi.org/project/holoscan/#history)
+RUN apt-get install -y --no-install-recommends --no-install-suggests \
+        holoscan={{ holoscan_sdk_filename }} \
+    # && apt-get remove -y g++ g++-11 gcc gcc-11 gcc-11-base build-essential \
+    && rm -rf /var/lib/apt/lists/*
+
 {% endif %}
+
+{% endif %}
+
+
+{% if holoscan_deb_arch == "arm64" %}
+# Requires libnuma on aarch64
+RUN apt update \
+    && apt-get install -y --no-install-recommends --no-install-suggests \
+        libnuma1="2.0.14-*" \
+    && rm -rf /var/lib/apt/lists/*
+{% endif %}
+
 
 RUN groupadd -f -g $GID $UNAME
 RUN useradd -rm -d /home/$UNAME -s /bin/bash -g $GID -G sudo -u $UID $UNAME
-RUN chown -R holoscan {{ working_dir }}
-RUN chown -R holoscan {{ full_input_path }}
-RUN chown -R holoscan {{ full_output_path }}
+RUN chown -R holoscan {{ working_dir }} && \
+    chown -R holoscan {{ full_input_path }} && \
+    chown -R holoscan {{ full_output_path }}
 
 # Set the working directory
 WORKDIR {{ working_dir }}
@@ -119,20 +386,14 @@ WORKDIR {{ working_dir }}
 COPY ./tools {{ working_dir }}/tools
 RUN chmod +x {{ working_dir }}/tools
 
-
-# Copy gRPC health probe
-{% if health_probe is defined %}
-
-RUN curl -L -o /bin/grpc_health_probe {{ health_probe | pprint }} \
-    && chmod +x /bin/grpc_health_probe && ls -l /bin/grpc_health_probe
-
-HEALTHCHECK --interval=10s --timeout=1s \
-    CMD /bin/grpc_health_probe -addr=:8777 || exit 1
-{% endif %}
+# Set the working directory
+WORKDIR {{ working_dir }}
 
 USER $UNAME
 
-ENV PATH=/root/.local/bin:/home/holoscan/.local/bin:/opt/nvidia/holoscan:$PATH
+ENV PATH=/home/${UNAME}/.local/bin:/opt/nvidia/holoscan/bin:$PATH
+ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:{{ app_dir }}:/home/${UNAME}/.local/lib/python3.10/site-packages/holoscan/lib
+ENV PYTHONPATH="{{ app_dir }}:${PYTHONPATH}"
 
 {% if application_type == 'PythonModule' or application_type == 'PythonFile' %}
 COPY ./pip/requirements.txt /tmp/requirements.txt
@@ -140,33 +401,31 @@ COPY ./pip/requirements.txt /tmp/requirements.txt
 RUN pip install --upgrade pip
 RUN pip install --no-cache-dir --user -r /tmp/requirements.txt
 
-{#  Use Holoscan SDK in the image unless specified by the user.
-For MONAI Deploy, the APP SDK will install it unless user specifies the Holoscan SDK file. #}
 {% if sdk_type == 'holoscan' %}
+# Install Holoscan SDK
 
-    {% if custom_holoscan_sdk == True %}
+{% if custom_holoscan_sdk == True %}
 # Copy user-specified Holoscan SDK wheel file
 COPY ./{{ holoscan_sdk_filename }} /tmp/{{ holoscan_sdk_filename }}
 RUN pip install /tmp/{{ holoscan_sdk_filename }}
-    {% elif custom_base_image == True %}
-# Install Holoscan SDK wheel from PyPI
-RUN pip install holoscan=={{ holoscan_sdk_version }}
-    {% else %}
-# Use embedded Holoscan SDK
-{# no op here #}
-    {% endif %}
-{% else %}
-# MONAI Deploy
 
-    {% if custom_monai_deploy_sdk %}
+{% else %}
+# Install Holoscan SDK wheel from PyPI
+RUN pip install holoscan=={{holoscan_sdk_filename}}
+{% endif %}
+{% else %}
+
+# Install MONAI Deploy App SDK
+{% if custom_monai_deploy_sdk == True %}
 # Copy user-specified MONAI Deploy SDK file
 COPY ./{{ monai_deploy_sdk_filename }} /tmp/{{ monai_deploy_sdk_filename }}
 RUN pip install /tmp/{{ monai_deploy_sdk_filename }}
-    {% else %}
+{% else %}
+
 # Install MONAI Deploy from PyPI org
 RUN pip install monai-deploy-app-sdk=={{ monai_deploy_app_sdk_version }}
-    {% endif %}
 
+{% endif %}
 {% endif %}
 {% endif %}
 
@@ -174,7 +433,7 @@ RUN pip install monai-deploy-app-sdk=={{ monai_deploy_app_sdk_version }}
 COPY ./models  {{ models_dir }}
 {% endif %}
 
-{%- if docs is defined %}
+{% if docs is defined %}
 COPY ./docs  {{ docs_dir }}
 {% endif %}
 
